language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e49d40b43bbb00a91626
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
